const modal=document.getElementById('orderModal');
const productSelect=document.getElementById('product');
const paymentAfterOrder=document.getElementById('paymentAfterOrder');
const GITHUB_USER='Tohidkhan6332';
const PAYMENT_UPI='7849917350.wallet@phonepe';
const PAYMENT_BINANCE='1123760641';
function openOrder(product){if(!modal)return;modal.classList.add('show');modal.setAttribute('aria-hidden','false');if(product&&productSelect)productSelect.value=product;resetPayment();const name=document.getElementById('name');if(name)setTimeout(()=>name.focus(),50)}
function closeOrder(){if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
function resetPayment(){if(paymentAfterOrder){paymentAfterOrder.hidden=true;paymentAfterOrder.innerHTML=''}const sent=document.getElementById('sent');if(sent)sent.hidden=true;if(document.getElementById('orderForm'))document.getElementById('orderForm').hidden=false}
if(modal){modal.addEventListener('click',e=>{if(e.target===modal)closeOrder()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeOrder()})}
const orderForm=document.getElementById('orderForm');
if(orderForm){orderForm.addEventListener('submit',async e=>{e.preventDefault();const product=productSelect?.value||'Custom request',name=document.getElementById('name')?.value.trim()||'',contact=document.getElementById('contactInput')?.value.trim()||'',req=document.getElementById('requirements')?.value.trim()||'';const orderId='TD-'+Date.now().toString().slice(-8);const orderText=`Order ID: ${orderId}\nProduct / service: ${product}\nName: ${name}\nContact: ${contact}\n\nRequirements:\n${req}`;try{await navigator.clipboard.writeText(orderText)}catch{}const sent=document.getElementById('sent');if(sent){sent.hidden=false;sent.textContent=`Order ${orderId} prepared. Details copied — send them to Tohid for confirmation.`}orderForm.hidden=true;showPayment(orderId,product)})}
function showPayment(orderId,product){if(!paymentAfterOrder)return;const qrData=`upi://pay?pa=${PAYMENT_UPI}&pn=Tohid%20Developer&cu=INR`;const qrUrl=`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(qrData)}`;paymentAfterOrder.hidden=false;paymentAfterOrder.innerHTML=`<div class="payment-after-head"><div class="eyebrow">PAYMENT OPTIONS</div><h3>Order ${orderId} — ${escapeHtml(product)}</h3><p>Your order request has been submitted. Pay only after the final amount is confirmed.</p></div><div class="pay-grid"><div class="pay-method"><strong>UPI</strong><p>Send payment to this UPI ID</p><button type="button" class="copy-pay" data-copy="${PAYMENT_UPI}">${PAYMENT_UPI}<small>Copy</small></button><a class="upi-open" href="${qrData}">Open UPI app →</a></div><div class="pay-method"><strong>Binance</strong><p>Binance ID</p><button type="button" class="copy-pay" data-copy="${PAYMENT_BINANCE}">${PAYMENT_BINANCE}<small>Copy</small></button></div><div class="pay-qr"><img src="${qrUrl}" alt="UPI payment QR code" loading="lazy" onerror="this.style.display='none'"><small>Scan to pay with UPI</small></div></div><div class="payment-note">After payment, keep your transaction/reference ID and send it with <b>${orderId}</b> to confirm the order.</div>`;paymentAfterOrder.querySelectorAll('.copy-pay').forEach(btn=>btn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(btn.dataset.copy);const old=btn.innerHTML;btn.innerHTML='Copied ✓';setTimeout(()=>btn.innerHTML=old,1200)}catch{}}));paymentAfterOrder.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function loadGitHubProjects(){const grid=document.querySelector('.project-grid');if(!grid)return;try{const res=await fetch(`https://api.github.com/users/${GITHUB_USER}/repos?sort=updated&per_page=6`,{headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw new Error('GitHub API unavailable');const repos=await res.json(),featured=repos.filter(r=>!r.fork).slice(0,4);if(!featured.length)return;grid.innerHTML=featured.map(r=>`<article><span>${escapeHtml((r.language||'CODE').toUpperCase())}</span><h3>${escapeHtml(r.name)}</h3><p>${escapeHtml(r.description||'Open-source project by Tohid Developer.')}</p><a href="${r.html_url}" target="_blank" rel="noreferrer">GitHub ↗</a></article>`).join('')}catch(err){console.info('GitHub projects fallback:',err.message)}}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
loadGitHubProjects();
