const T={en:{q:'Quran',h:'Hadith',d:'Duas & Azkar',p:'Prayer Times'},hi:{q:'कुरआन',h:'हदीस',d:'दुआएँ और अज़कार',p:'नमाज़ के समय'},ur:{q:'قرآن',h:'حدیث',d:'دعائیں اور اذکار',p:'نماز کے اوقات'},ar:{q:'القرآن',h:'الحديث',d:'الأدعية والأذكار',p:'أوقات الصلاة'}};
const surahs=[['1','Al-Fatihah','الفاتحة',7],['2','Al-Baqarah','البقرة',286],['3','Aal-E-Imran','آل عمران',200],['4','An-Nisa','النساء',176],['5',"Al-Ma'idah",'المائدة',120],['6',"Al-An'am",'الأنعام',165],['7',"Al-A'raf",'الأعراف',206],['8','Al-Anfal','الأنفال',75],['9','At-Tawbah','التوبة',129],['10','Yunus','يونس',109],['11','Hud','هود',123],['12','Yusuf','يوسف',111]];
const hadith=[['Sahih al-Bukhari','Authentic collection of Imam al-Bukhari'],['Sahih Muslim','Authentic collection of Imam Muslim'],["Jami' at-Tirmidhi",'Hadith collection of Imam at-Tirmidhi'],['Sunan Abi Dawud','Hadith collection of Abu Dawud'],['Sunan Ibn Majah','Hadith collection of Ibn Majah']];
const duas=[['Morning Azkar','Daily remembrance after Fajr.'],['Evening Azkar','Daily remembrance around Maghrib.'],['Before Sleeping','Supplications for the night.'],['After Prayer','Dhikr after obligatory prayers.'],['Travel Dua','Supplication for travelling.']];
const $=s=>document.querySelector(s); const current=()=>localStorage.getItem('til-lang')||'en';
function renderSurahs(){const q=$('#surahSearch').value.toLowerCase();$('#surahList').innerHTML=surahs.filter(s=>(s[1]+' '+s[2]).toLowerCase().includes(q)).map(s=>`<article class="surah" data-id="${s[0]}"><span class="surah-num">${s[0]}</span><span class="surah-ar">${s[2]}</span><div class="surah-name">${s[1]}</div><div class="muted">${s[3]} Ayahs</div></article>`).join('');document.querySelectorAll('.surah').forEach(e=>e.onclick=()=>openReader(e.dataset.id))}
function renderHadith(){$('#hadithGrid').innerHTML=hadith.map(x=>`<article class="collection"><div>📚</div><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}
function renderDuas(){$('#duaGrid').innerHTML=duas.map(x=>`<article class="dua"><div>🤲</div><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}
function renderPrayer(){const p=[['Fajr','05:02'],['Dhuhr','12:35'],['Asr','16:10'],['Maghrib','18:48'],['Isha','20:06']];$('#prayerGrid').innerHTML=p.map(x=>`<div class="prayer"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}
function openReader(id){const s=surahs.find(x=>x[0]===id);$('#reader').classList.remove('hidden');$('#readerTitle').textContent=s[1];$('#readerMeta').textContent=`Surah ${s[0]} · ${s[3]} Ayahs`;const sample=['الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ','الرَّحْمَٰنِ الرَّحِيمِ','مَالِكِ يَوْمِ الدِّينِ','إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ','اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ','صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ','غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ','وَلَا الضَّالِّينَ'];$('#ayahs').innerHTML=sample.map((a,i)=>`<article class="ayah"><div class="ayah-num">${i+1}</div><div class="ayah-ar">${a}</div><div class="ayah-en">Connect a verified multilingual Quran source for production translation.</div></article>`).join('');$('#reader').scrollIntoView({behavior:'smooth'})}
function applyLanguage(){const l=current();document.documentElement.lang=l;document.documentElement.dir=['ar','ur'].includes(l)?'rtl':'ltr';$('#language').value=l;const t=T[l];const nav=document.querySelectorAll('.desktop-nav a');if(nav.length>=4){nav[0].textContent=t.q;nav[1].textContent=t.h;nav[2].textContent=t.d;nav[3].textContent=t.p}renderSurahs();renderHadith();renderDuas();renderPrayer()}
$('#language').onchange=e=>{localStorage.setItem('til-lang',e.target.value);applyLanguage()};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('til-theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('til-theme')==='dark')document.body.classList.add('dark');$('#surahSearch').oninput=renderSurahs;$('#closeReader').onclick=()=>$('#reader').classList.add('hidden');let fs=30;$('#fontUp').onclick=()=>{$('.ayah-ar').style.fontSize=(fs+=2)+'px'};$('#fontDown').onclick=()=>{$('.ayah-ar').style.fontSize=(fs=Math.max(20,fs-2))+'px'};$('#tasbeeh').onclick=()=>$('#tasbeeh').textContent=+$('#tasbeeh').textContent+1;$('#locateBtn').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>$('#locationText').textContent=`Location detected: ${p.coords.latitude.toFixed(3)}, ${p.coords.longitude.toFixed(3)}`,()=>$('#locationText').textContent='Location permission denied.'):$('#locationText').textContent='Geolocation unavailable.';applyLanguage();